import type { OptimizationBudget, ResolvedConfig, ValidationIssue } from '../core/model/types';
import type { AstIssue } from '../core/validation/ast/types';

/**
 * Detailed quality evaluation result for a single fixture item.
 */
export interface QualityEvaluationResult {
  readonly fixtureId: string;
  readonly rawSyntaxValid: boolean;
  readonly optimizedSyntaxValid: boolean;
  readonly syntaxPreserved: boolean;
  readonly rawAstIssues: ReadonlyArray<AstIssue>;
  readonly optimizedAstIssues: ReadonlyArray<AstIssue>;
  readonly keySymbolPreservationRatio: number;
  readonly tokenSimilarityScore: number;
  readonly overallPassed: boolean;
}

/**
 * Alias for QualityEvaluationResult.
 */
export type QualityEvalResult = QualityEvaluationResult;

/**
 * Aggregated quality report for a dataset run.
 */
export interface DatasetQualityReport {
  readonly totalItems: number;
  readonly rawPassRate: number;
  readonly optimizedPassRate: number;
  readonly passRateDelta: number;
  readonly avgKeySymbolPreservation: number;
  readonly avgTokenSimilarity: number;
  readonly evaluations: ReadonlyArray<QualityEvaluationResult>;
}

/**
 * Configuration options for a single benchmark budget sweep.
 */
export interface BenchmarkSweepConfig {
  readonly sweepId: string;
  readonly budget: OptimizationBudget;
}

/**
 * Configuration parameters for BenchmarkRunner.run().
 */
export interface BenchmarkRunnerConfig {
  readonly baseConfig: ResolvedConfig;
  readonly sweeps: ReadonlyArray<BenchmarkSweepConfig>;
  readonly evaluateQuality?: boolean;
  readonly runsPerFixture?: number;
}

/**
 * Execution result for a single fixture under a specific budget sweep.
 */
export interface FixtureRunResult {
  readonly fixtureId: string;
  readonly sweepId: string;
  readonly inputTokens: number;
  readonly outputTokens: number;
  readonly tokenReductionRatio: number;
  readonly fallbackUsed: boolean;
  readonly fallbackReason?: string;
  readonly latencyMs: number;
  readonly validationPassed: boolean;
  readonly validationIssues: ReadonlyArray<ValidationIssue>;
  readonly qualityResult?: QualityEvaluationResult;
}

/**
 * Alias for FixtureRunResult.
 */
export type BenchmarkItemReport = FixtureRunResult;

/**
 * Aggregated summary metrics for a benchmark sweep or overall run.
 */
export interface BenchmarkMetricSummary {
  readonly totalFixtures: number;
  readonly totalRuns: number;
  readonly avgReductionRatio: number;
  readonly fallbackRate: number;
  readonly avgLatencyMs: number;
  readonly p95LatencyMs: number;
  readonly syntaxPassRate: number;
  readonly totalValidationIssues: number;
}

/**
 * Aggregated outcome of a single budget sweep across all dataset fixtures.
 */
export interface SweepResult {
  readonly sweepId: string;
  readonly budget: OptimizationBudget;
  readonly summary: BenchmarkMetricSummary;
  readonly itemResults: ReadonlyArray<FixtureRunResult>;
}

/**
 * Comprehensive report generated by BenchmarkRunner.run().
 */
export interface BenchmarkReport {
  readonly timestamp: string;
  readonly datasetName: string;
  readonly totalFixtures: number;
  readonly overallSummary: BenchmarkMetricSummary;
  readonly sweepResults: ReadonlyArray<SweepResult>;
  readonly environment: {
    readonly nodeVersion: string;
    readonly platform: string;
    readonly tokendamperVersion: string;
  };
}
